### ISSUE TITLE
Executable API KEY

### ISSUE THREAD

**Issue by onurhan1337** [yigitozdamar/crypto-app#1]
https://github.com/yigitozdamar/crypto-app/blob/17c5597298d96b87d6d9ee0b69f6117b3497a579/src/services/cryptoApi.js#L5

This may not harm you, but api requests can be made or used on your behalf. You can store your private api key in the **.env** file content. If you do not know how to do this, you can learn from the link I left below.
```
https://create-react-app.dev/docs/adding-custom-environment-variables/
```

**Comment by yigitozdamar** [comment]
Thanks bro 🙋‍♂️

iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________
Gönderen: Onur1337 ***@***.***>
Gönderildi: Saturday, March 26, 2022 12:00:25 PM
Kime: yigitozdamar/crypto-app ***@***.***>
Bilgi: Subscribed ***@***.***>
Konu: [yigitozdamar/crypto-app] Executable API KEY (Issue #1)


https://github.com/yigitozdamar/crypto-app/blob/17c5597298d96b87d6d9ee0b69f6117b3497a579/src/services/cryptoApi.js#L5

This may not harm you, but api requests can be made or used on your behalf. You can store your private api key in the .env file content. If you do not know how to do this, you can learn from the link I left below.

https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by onurhan1337** [comment]
You're welcome.
